name: CI/CD Frontend - Angular (Render)

on:
  push:
    branches:
      - testing
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yaml" 

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build Angular (production)
        working-directory: frontend
        run: npm run build -- --configuration production

      - name: Trigger Render Deploy
        env:
          RENDER_HOOK: ${{ secrets.RENDER_FRONTEND_HOOK }}
        run: |
          if [ -z "$RENDER_HOOK" ]; then
            echo " RENDER_FRONTEND_HOOK is empty"
            exit 1
          fi
          curl -X POST "$RENDER_HOOK"
